In [14]:
import json
import pandas as pd

with open('json_data/2019_pass_or_fail.json', encoding='UTF8') as file:
    dataset = json.load(file)

In [15]:
# DataFrame 생성
df = pd.DataFrame(dataset)

# 대학별 데이터 개수 확인
university_counts = df['대학명'].value_counts()

# 결과 출력
print(university_counts)

대학명
중앙대(서울)       5896
가천대(글로벌)      5471
건국대(서울)       5437
성균관대          5239
동국대(서울)       4765
한양대(서울)       4087
인하대           4073
연세대(서울)       3795
경희대(서울)       3637
세종대           3531
서강대           3429
고려대(서울)       3345
숭실대           3267
한성대           3257
홍익대(세종)       3145
이화여대          3075
서경대           3024
광운대           2811
홍익대(서울)       2757
서울여대          2756
삼육대           2631
숙명여대          2559
서울과학기술대       2483
국민대           2439
성신여대          2393
경희대(국제)       2348
한양대(에리카)      2279
수원대           2226
단국대(죽전)       2121
한국외대(서울)      2011
가톨릭대(성심)      1887
서울시립대         1825
을지대(성남)       1674
아주대           1665
서울대           1662
신한대(의정부)      1650
대진대           1612
덕성여대          1586
경기대(수원)       1562
성결대           1436
상명대(서울)       1404
고려대(세종)       1376
동덕여대          1365
한국산업기술대       1337
명지대(서울)       1212
한신대           1101
강원대(춘천)       1068
백석대           1059
가천대(메디컬)       995
연세대(미래)        951
단국대(천안)        908
평택대            875
강남대            820
용인대            790
명지대(용인)        781
상지대            771
한국외대(글로벌)      706
안양대(안양)        684
상명대(천안)        675
극동대            670
한국항공대          647
중부대(고양)        643
한림대            629
건국대(글로컬)       624
한서대            611
남서울대           589
순천향대           578
중앙대(안성)        570
선문대            527
인천대            510
우송대            505
경기대(서울)        501
협성대            478
경동대(양주)        477
가톨릭관동대         449
신한대(동두천)       445
호서대(아산)        434
가톨릭대(성의)       415
배재대            387
한국성서대          384
경동대(원주문막)      379
청주대            361
세명대            360
경북대(대구)        356
부산대            325
한경대            320
중부대(충청)        318
충남대            313
원광대            311
충북대            308
호원대            307
한라대            285
나사렛대           283
한국예술종합학교       280
중원대            266
KAIST          258
한세대            252
청운대(홍성)        251
동국대(경주)        237
한국교통대(충주)      237
동양대(동두천)       230
KC대            229
강릉원주대(강릉)      222
호서대(천안)        220
서원대            214
성공회대           214
전북대(전주)        201
대전대            198
서울신학대          188
조선대            187
공주대(공주)        178
목원대            177
우석대(완주)        174
차의과학대          174
청운대(인천)        169
동양대(영주)        163
강원대(삼척)        163
유원대            157
총신대            156
한국체육대          144
서울한영대          141
울산대            132
을지대(대전)        123
초당대            120
강릉원주대(원주)      116
신경대            115
건양대(대전)        115
강원대(도계)        115
세한대(당진)        111
한국기술교육대        108
춘천교대           107
전남대(광주)        106
GIST           105
경인교대           103
서울교대           103
UNIST          102
한남대             96
계명대             93
전주대             91
건양대(논산)         90
제주대             89
호남대             87
공주대(천안)         85
한동대             82
한국해양대           82
우석대(진천)         81
한국교원대           81
부산외국어대          77
포항공과대           76
DGIST           72
목포해양대           69
대구대             64
예원예술대(양주)       64
김천대             63
대구가톨릭대          60
대구한의대           58
경상대             57
동아대             55
영남대             54
청주교대            54
공주대(예산)         54
광주대             52
경성대             49
육군사관학교          48
경운대             47
광주여대            47
한국교통대(증평)       46
경일대             45
동의대             45
경동대(고성)         44
예원예술대(전북)       44
루터대             40
안동대             39
군산대             39
추계예술대           39
장로회신학대          38
한국교통대(의왕)       38
경남대             37
남부대             37
순천대             36
감리교신학대          36
한밭대             34
안양대(강화)         34
공주교대            34
인천가톨릭대(송도)      34
전남대(여수)         33
동신대             33
공군사관학교          32
동명대             32
세한대(영암)         31
진주교대            29
금오공과대           28
송원대             27
부산가톨릭대          26
고신대             26
인제대(김해)         26
경북대(상주)         25
목포대             24
아세아연합신학대        24
광주교대            22
신라대             22
부경대             21
서울기독대           21
칼빈대             21
대구교대            19
서울장신대           19
부산교대            18
위덕대             18
해군사관학교          17
호서대(당진)         17
가야대             16
한국국제대           15
전북대(특성화)        14
동서대             13
경주대             12
경남과학기술대         12
침례신학대           10
한일장신대           10
국군간호사관학교         9
경찰대학             8
한려대              8
창신대              7
꽃동네대             6
한국전통문화대          6
대구예술대            6
영산대(양산)          5
목포가톨릭대           5
창원대              5
영산대(부산)          5
제주국제대            4
인제대(부산)          4
전주교대             3
가톨릭대(성신)         3
예수대              2
대전신학대            1
Name: count, dtype: int64

In [17]:
# 상위 10개 데이터 출력
top_10 = university_counts.head(10)
print("상위 10개 데이터:")
print(top_10)

# 하위 10개 데이터 출력
bottom_10 = university_counts.tail(10)
print("\n하위 10개 데이터:")
print(bottom_10)

상위 10개 데이터:
대학명
중앙대(서울)     5896
가천대(글로벌)    5471
건국대(서울)     5437
성균관대        5239
동국대(서울)     4765
한양대(서울)     4087
인하대         4073
연세대(서울)     3795
경희대(서울)     3637
세종대         3531
Name: count, dtype: int64

하위 10개 데이터:
대학명
영산대(양산)     5
목포가톨릭대      5
창원대         5
영산대(부산)     5
제주국제대       4
인제대(부산)     4
전주교대        3
가톨릭대(성신)    3
예수대         2
대전신학대       1
Name: count, dtype: int64